"""
seed_select.py — NETEXEC
=========================
Seed-chooser screen, shown first when starting a new game (before difficulty
and executive selection). The flow is:

    MENU -> SEED_SELECT -> DIFFICULTY -> EXECUTIVE_SELECT -> PLAYING

A run's master seed governs every random draw (shop, rerolls, seasonal rolls),
so two runs with the same seed (and the same difficulty + executive) play out
identically. A random seed is generated by default; the player may type a custom
one or hit RANDOMIZE. Typing is handled in GameUI._handle_key while this screen
is active.
"""

import random
import pygame

from engine.constants import (
    C_GREEN_BRIGHT, C_GREEN_MID, C_GREEN_PANEL, C_AMBER_DIM,
    C_WHITE, C_CYAN,
)
from ..screen_enum import GameScreen
from ..widgets import draw_button, draw_text_wrapped
from .base import Screen

SEED_MAX = 2 ** 31            # exclusive upper bound for a seed
_MAX_DIGITS = 10


def ensure_seed_str(ctx):
    """Make sure ctx has a seed input string, seeded from a fresh random value."""
    if getattr(ctx, "_seed_input_str", None) is None:
        base = getattr(ctx, "_pending_seed", None)
        if base is None:
            base = random.randrange(SEED_MAX)
        ctx._pending_seed   = int(base)
        ctx._seed_input_str = str(int(base))


def randomize(ctx):
    """Roll a new random seed into the input field."""
    ctx._pending_seed   = random.randrange(SEED_MAX)
    ctx._seed_input_str = str(ctx._pending_seed)


def commit_seed_and_continue(ctx):
    """Parse the typed seed (or roll one if blank) and advance to difficulty."""
    s = (getattr(ctx, "_seed_input_str", "") or "").strip()
    seed = int(s) % SEED_MAX if s.isdigit() and s != "" else random.randrange(SEED_MAX)
    ctx._pending_seed   = seed
    ctx._seed_input_str = str(seed)
    ctx.set_screen(GameScreen.DIFFICULTY)


class SeedSelectScreen(Screen):
    def render(self, ctx, state):
        render(ctx, state)


def render(ctx, state):
    ensure_seed_str(ctx)
    cx = ctx._sw // 2
    cy = ctx._sh // 2

    hdr = ctx._f("header").render("CHOOSE YOUR RUN SEED", True, C_GREEN_BRIGHT)
    ctx.screen.blit(hdr, hdr.get_rect(center=(cx, cy - 150)))

    draw_text_wrapped(
        ctx.screen,
        "Every run is governed by a SEED. The same seed (with the same difficulty "
        "and executive) replays an identical game - same shop, same draws. A random "
        "seed is picked for you; type your own below or hit RANDOMIZE.",
        pygame.Rect(cx - 260, cy - 118, 520, 80),
        ctx._f("small"), C_AMBER_DIM,
    )

    # ── Seed input field ──────────────────────────────────────────────────────
    box = pygame.Rect(cx - 220, cy - 28, 440, 58)
    pygame.draw.rect(ctx.screen, C_GREEN_PANEL, box, border_radius=6)
    pygame.draw.rect(ctx.screen, C_CYAN,        box, 2, border_radius=6)

    seed_str = ctx._seed_input_str or ""
    # Blinking caret while on this screen.
    caret = "_" if (ctx._tick_ms // 500) % 2 == 0 else " "
    txt   = ctx._f("title").render(seed_str + caret, True, C_WHITE)
    # Clamp very long strings to fit the box.
    if txt.get_width() > box.width - 24:
        txt = ctx._f("header").render(seed_str + caret, True, C_WHITE)
    ctx.screen.blit(txt, txt.get_rect(midleft=(box.x + 14, box.centery)))

    hint = ctx._f("micro").render("type digits  -  BACKSPACE to edit  -  ENTER to confirm",
                                  True, C_GREEN_MID)
    ctx.screen.blit(hint, hint.get_rect(center=(cx, box.bottom + 16)))

    # ── Buttons ───────────────────────────────────────────────────────────────
    rnd_rect  = pygame.Rect(cx - 220, cy + 60, 210, 44)
    cont_rect = pygame.Rect(cx + 10,  cy + 60, 210, 44)
    draw_button(ctx, rnd_rect,  "RANDOMIZE",  lambda: randomize(ctx),               border_color=C_AMBER_DIM)
    draw_button(ctx, cont_rect, "CONTINUE >", lambda: commit_seed_and_continue(ctx), border_color=C_CYAN)

    back_rect = pygame.Rect(20, 20, 100, 36)
    draw_button(ctx, back_rect, "< BACK", lambda: ctx.set_screen(GameScreen.MENU))
